### ISSUE TITLE
Cant build due to test failure on method shouldAllowBackgroundThreadsToFinishUsingContextAfterOnDestroy

### ISSUE THREAD

**Issue by mattwhetton** [rtyley/roboguice-sherlock#15]
Full stack trace below

Test set: com.github.rtyley.android.sherlock.roboguice.activity.SherlockActivityInjectionTest

Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.578 sec <<< FAILURE!
    shouldAllowBackgroundThreadsToFinishUsingContextAfterOnDestroy(com.github.rtyley.android.sherlock.roboguice.activity.SherlockActivityInjectionTest)  Time elapsed: 0.04 sec  <<< ERROR!
    java.lang.NegativeArraySizeException
        at com.github.rtyley.android.sherlock.roboguice.activity.SherlockActivityInjectionTest.shouldAllowBackgroundThreadsToFinishUsingContextAfterOnDestroy(SherlockActivityInjectionTest.java:142)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at com.xtremelabs.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:292)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

**Comment by rtyley** [comment]
Hi @mattwhetton, I've added a Travis CI build to verify that that the project builds independently of my own setup. As you can see, the build is currently succeeding:

https://travis-ci.org/rtyley/roboguice-sherlock/builds/6179832

I had to do a bit of mucking around in Travis to get this working though, with the first couple of builds failing. None of the failed builds had your `java.lang.NegativeArraySizeException` so far as I could see.

If you check the Travis CI configuration we're using, and ensure you have all the relevant Android packages, you'll stand a good chance of getting the tests to pass:

https://github.com/rtyley/roboguice-sherlock/blob/master/.travis.yml

Note also that RoboGuice-Sherlock jars are published on Maven Central, so you don't have to build it unless you're working on RoboGuice-Sherlock itself:

http://search.maven.org/#artifactdetails%7Ccom.github.rtyley%7Croboguice-sherlock%7C1.5%7Cjar

**Comment by mattwhetton** [comment]
Thanks for the help - I didn't realise the jars were on maven central - I'll use from there!
