### ISSUE TITLE
Unable to use no_aop guice classifier

### ISSUE THREAD

**Issue by mrmarbles** [rtyley/roboguice-sherlock#17]
I'm getting the below "warning" when launching  my app with the roboguice-sherlock dependency.  After a bit of research (https://groups.google.com/forum/#!topic/google-guice/rCfmJR4Ru68) it appears to be due to the built-in AOP support in roboguice 3.0.  Normally, you can specify `<classifier>no_aop</classifier>` on the guice dependency in the pom to get around this - when not using actionbarsherlock API's.  It would be nice to be able to work with the same classified dependency to eliminate this warning.

```
07-02 15:41:37.444: WARN/nalizableReferenceQueue(364): Could not load Finalizer in its own class loader. Loading Finalizer in the current class loader instead. As a result, you will not be able to garbage collect this class loader. To support reclaiming this class loader, either resolve the underlying issue, or move Google Collections to your system class path.
        java.io.FileNotFoundException: com/google/inject/internal/util/$Finalizer.class
        at com.google.inject.internal.util.$FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:269)
        at com.google.inject.internal.util.$FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:253)
        at com.google.inject.internal.util.$FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:175)
        at com.google.inject.internal.util.$FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:100)
        at com.google.inject.internal.util.$MapMaker$QueueHolder.<clinit>(MapMaker.java:787)
        at com.google.inject.internal.util.$MapMaker$WeakEntry.<init>(MapMaker.java:946)
        at com.google.inject.internal.util.$MapMaker$Strength$1.newEntry(MapMaker.java:312)
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.newEntry(MapMaker.java:498)
        at com.google.inject.internal.util.$MapMaker$StrategyImpl.newEntry(MapMaker.java:419)
        at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2029)
        at com.google.inject.internal.Annotations$AnnotationChecker.hasAnnotations(Annotations.java:116)
        at com.google.inject.internal.Annotations.isBindingAnnotation(Annotations.java:180)
        at com.google.inject.Key.ensureIsBindingAnnotation(Key.java:366)
        at com.google.inject.Key.strategyFor(Key.java:338)
        at com.google.inject.Key.get(Key.java:272)
        at com.google.inject.internal.AbstractBindingBuilder.annotatedWithInternal(AbstractBindingBuilder.java:82)
        at com.google.inject.internal.ConstantBindingBuilderImpl.annotatedWith(ConstantBindingBuilderImpl.java:49)
        at roboguice.config.DefaultRoboModule.configure(DefaultRoboModule.java:117)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.spi.Elements.getElements(Elements.java:78)
        at roboguice.RoboGuice.setBaseApplicationInjector(RoboGuice.java:83)
        at roboguice.RoboGuice.setBaseApplicationInjector(RoboGuice.java:139)
        at roboguice.RoboGuice.getBaseApplicationInjector(RoboGuice.java:59)
        at roboguice.RoboGuice.getInjector(RoboGuice.java:149)
        at com.github.rtyley.android.sherlock.roboguice.activity.RoboSherlockActivity.onCreate(RoboSherlockActivity.java:59)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.access$2300(ActivityThread.java:125)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4627)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rtyley** [comment]
Hi @mrmarbles, thanks for the bug report. I have limited time at the moment to address this issue, but I see you say "built-in AOP support in roboguice 3.0." - I believe RoboGuice 3.0 has not been released yet, do you mean _Guice_ 3.0?

**Comment by JakeWharton** [comment]
I don't think this is AOP related. The class in question (FinalizableReferenceQueue) is one full of magic and delight which basically provides a callback to when objects are being garbage collected on a background thread to allow for secondary cleanup. The error is likely due to the restrictions and/or limitations on the class loading capabilities of Android.

The problem most certainly is not in this library which is basically just a shim between two others for convenience.

The real fix would be for Roboguice (or even upstream in Guice) to replace this behavior with one that operates under the constraints of Android without attempting a lot of the magic that is only available on the JVM. In either case, this is just a warning, not an error, and is certainly safe to ignore. You should be able to suppress its output using the facilities in the `Logger` API.
